on: 
  push: 
    branches:
      - master
on: 
  push: 
    branches: 
      - add-deployment-github-action
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Bootstrap all services 
        run: npm run bootstrap
      - name: Deploy the web service
        run: npm run deploy --prefix services/web
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
